### ISSUE TITLE
MC 1.8.9 incompatibility

### ISSUE THREAD

**Issue by zsawyer** [zsawyer/MumbleLink#10]
> It seems that MumbleLink for MC 1.8 does not work on MC 1.8.9 and/or the newest Java.

[Robijnvogel](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272675-1-8-mumblelink-forge-smp-lan-mumble-realism?comment=444)

**Comment by zsawyer** [comment]
This incompatibility is with **FML** itself (not MC nor Java). 
The problem seems to be that EPAS is activated before MumbleLink now for some reason. 
Also they have now implemented mod activation features which uses my `Activateable.activate`-function inadvertently (this is extremely closely related to #6). 

I will have to look into the dependency management. Trials with simply manipulating the mod.info did not succeed sofar. I might have to go into an dig into them mods' annotations. 

`mumbleLinkInstance` or `mumbleLinkInstance.getApi()` returns `null` because MumbleLink was not initialized before EPAS resulting in this line being called too early: [zsawyer.mods.mumblelink.addons.pa.es.ExtendedPASupport.activate(ExtendedPASupport.java:117)](https://github.com/zsawyer/MumbleLink/blob/master/addons/EPAS/src/main/java/zsawyer/mods/mumblelink/addons/pa/es/ExtendedPASupport.java#L117)

Relevant error message:

```
    java.lang.NullPointerException: Initializing game
        at zsawyer.mods.mumblelink.addons.pa.es.ExtendedPASupport.activate(ExtendedPASupport.java:117)
        at zsawyer.mods.mumblelink.addons.pa.es.ExtendedPASupport.load(ExtendedPASupport.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        [...]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:559)
        [...]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:729)
        at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
```
